Added new container: diamond-aligner
DNALinux/OmicsContainers pull request #8
Opened 2024-11-28 19:50 UTC by Facundo1224

Changes:
- Added a new container: diamond-aligner.

Additional notes:
- Merged main into testing after pushing this change because I forgot to pull before adding the container.

2024-11-28 20:21 UTC, sbassi commented
The code seems good, didn't test it yet. You need to move it into a directory named with the version name.
Instead of diamond-aligner/Dockerfile
should be:
diamond-aligner/2.1.9-debian/Dockerfile

2024-11-28 20:22 UTC, sbassi commented on diamond-aligner/Dockerfile
> +    upstream.version="2.1.10" \
upstream should be 2.1.9

2024-11-29 03:47 UTC, sbassi requested changes
The file is good, it works as is, but is better without the entry point, and there are minors changes required, so please address all comments.

2024-11-29 03:47 UTC, sbassi commented on diamond-aligner/Dockerfile
> +ENTRYPOINT ["diamond"]
Remove Entrypoint and CMD.

2024-11-29 03:47 UTC, sbassi commented on diamond-aligner/Dockerfile
> +ENV DEBIAN_FRONTEND=noninteractive
replace this line as suggested in the warning and delete the warning comment

2024-11-29 03:47 UTC, sbassi commented on diamond-aligner/Dockerfile
> +    upstream.version="2.1.10" \
in upstream, you can use:
2.1.9.163
Since this is what the program reports.

2024-11-29 08:04 UTC, Facundo1224 commented
Done! Changes in new commit:

- Adjusted file path to "diamond-aligner/2.1.9-debian/Dockerfile" (previously "diamond-aligner/Dockerfile")
- Corrected the "upstream.version" label to 2.1.9.163
- Removed the "ENTRYPOINT" and "CMD" layers from the Dockerfile.
- Removed leftover warning comment

2024-11-29 10:32 UTC, sbassi approved these changes

2024-11-29 10:33 UTC, merged